# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(default='', max_length=10, verbose_name='数据年份')),
                ('data_file1', models.FileField(upload_to='', verbose_name='数据附件1')),
                ('data_file2', models.FileField(upload_to='', verbose_name='数据附件2')),
                ('data_file3', models.FileField(upload_to='', verbose_name='数据附件3')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(default='', max_length=10, verbose_name='申请数据年份')),
                ('goal', models.CharField(default='', max_length=1000, verbose_name='申请目的')),
                ('certificate', models.FileField(upload_to='', verbose_name='上传申请表')),
                ('result', models.CharField(choices=[('审核中', '审核中'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过')], max_length=10, verbose_name='申请结果')),
                ('apply_date', models.DateTimeField(auto_now=True, verbose_name='申请时间')),
                ('check_date', models.DateTimeField(auto_now=True, verbose_name='审核时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('name', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('sex', models.CharField(default='', max_length=2, verbose_name='性别')),
                ('idcard', models.CharField(default='', max_length=20, verbose_name='身份证号')),
                ('org', models.CharField(default='', max_length=40, verbose_name='单位')),
                ('subject', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('zhicheng', models.CharField(default='', max_length=20, verbose_name='职称')),
                ('tele', models.CharField(default='', max_length=10, verbose_name='电话号码')),
                ('email', models.CharField(default='', max_length=30, verbose_name='邮箱')),
                ('adress', models.CharField(default='', max_length=40, verbose_name='地址')),
            ],
        ),
        migrations.AddField(
            model_name='userapply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.UserInfo'),
        ),
    ]
